package com.ulearning.ulearning_app.domain.model

data class Course(
    var amount: Int = 0,
    var asynchronousHour: String = "",
    var benefits: String = "",
    var category: Category = Category(),
    var categoryId: Int = 0,
    var certificate: Boolean = false,
    var code: String = "",
    var coupon: Any = Any(),
    var couponId: Any = Any(),
    var currency: String = "",
    var descriptionLarge: String = "",
    var descriptionShort: String = "",
    var discount: Any = Any(),
    var duration: String = "",
    var externalId: String = "",
    var externalLink: Any = Any(),
    var groups: List<Group> = listOf(),
    var id: Int = 0,
    var instructions: String = "",
    var isFree: Boolean = false,
    var isPurchased: Boolean = false,
    var isShop: Boolean = false,
    var languageId: Int = 0,
    var lessonsCount: Int = 0,
    var mainImage: MainImage = MainImage(),
    var methodology: String = "",
    var modality: String = "",
    var nature: String = "",
    var origin: String = "",
    var politicsLink: String = "",
    var presentationLink: String = "",
    var ratingAverage: Int = 0,
    var ratingCount: Int = 0,
    var record: Boolean = false,
    var scheduleLink: Any = Any(),
    var secondaryImages: List<SecondaryImage> = listOf(),
    var selfStudyHour: String = "",
    var slug: String = "",
    var studentsCount: Int = 0,
    var suspendedAt: Any = Any(),
    var syllabusLink: String = "",
    var synchronousHour: String = "",
    var target: String = "",
    var title: String = ""
)